update changes
Signed-off-by: Pierre Ugaz <ulm0@innersea.xyz>

diff --git a/docker/assets/wrapper b/docker/assets/wrapper
--- a/docker/assets/wrapper
+++ b/docker/assets/wrapper
@@ -17,6 +17,33 @@ function failed_pg_upgrade() {
     exit 1
 }
 
+function clean_stale_pids() {
+    # cleanup known pid/socket files
+    for x in /opt/gitlab/sv /run $(ls -d /tmp/gitaly-ruby* 2>/dev/null) ; do
+        # find
+        #  - any (s)ocket or regular (f)ile
+        #  - by the name of "*.pid" or "socket.?"
+        #  - and delete them
+        find $x \
+            \( \
+              -type f \
+              -o -type s \
+            \) \(\
+              -name pid \
+              -o -name "*.pid" \
+              -o -name "socket.?" \
+            \) \
+            -delete ;
+    done
+}
+
+function detect_unclean_start() {
+    set +e
+    echo "Cleaning stale PIDs & sockets"
+    clean_stale_pids
+    set -e
+}
+
 trap "sigterm_handler; exit" TERM
 
 source /RELEASE
@@ -43,6 +70,9 @@ echo "  docker exec -it gitlab update-permissions"
 echo "  docker restart gitlab"
 echo
 sleep 3s
+
+# Run unclean start detection & cleanup
+detect_unclean_start
 
 # Copy gitlab.rb for the first time
 if [[ ! -e /etc/gitlab/gitlab.rb ]]; then
@@ -73,38 +103,20 @@ echo "Preparing services..."
 rm -f /opt/gitlab/service/*
 ln -s /opt/gitlab/sv/sshd /opt/gitlab/service
 ln -sf /opt/gitlab/embedded/bin/sv /opt/gitlab/init/sshd
+mkdir -p /var/run/sshd
 mkdir -p /var/log/gitlab/sshd
+mkdir -p /var/log/gitlab/reconfigure
 
 # Start service manager
 echo "Starting services..."
 GITLAB_OMNIBUS_CONFIG= /opt/gitlab/embedded/bin/runsvdir-start &
 
-# Configure gitlab package
-# WARNING:
-# the preinst script has the database backup
-# It will not be executed, because all services are not yet started
-# They will be started when `reconfigure` is executed
-echo "Configuring GitLab package..."
-/var/lib/dpkg/info/${RELEASE_PACKAGE}.preinst upgrade
-
-# Patch sysctl config
-if [[ -e /opt/gitlab/embedded/cookbooks/package/resources/sysctl.rb ]]; then
-	echo "Patching sysctl config..."
-	sed -i -e 's/  | sysctl -e -p -//g' /opt/gitlab/embedded/cookbooks/package/resources/sysctl.rb
-fi
-
 echo "Configuring GitLab..."
 gitlab-ctl reconfigure
 
-# Make sure PostgreSQL is at the latest version.
-# If it fails, print a message with a workaround and exit
-if [ "${GITLAB_SKIP_PG_UPGRADE}" != true ]; then
-    gitlab-ctl pg-upgrade -w || failed_pg_upgrade
-fi
-
 if [ -n "${GITLAB_POST_RECONFIGURE_SCRIPT+x}" ]; then
-	echo "Runnning Post Reconfigure Script..."
-  	eval "${GITLAB_POST_RECONFIGURE_SCRIPT}"
+  echo "Running Post Reconfigure Script..."
+  eval "${GITLAB_POST_RECONFIGURE_SCRIPT}"
 fi
 
 # Tail all logs
